define([], function() {
  return {
    "PropertyPaneDescription": "Configure your RSS feed display settings",
    "LayoutGroupName": "Layout Settings",
    "TitleFieldLabel": "Web Part Title",
    "FeedUrlFieldLabel": "RSS Feed URL",
    "MaxItemsFieldLabel": "Maximum number of items to display",
    "AutoRefreshFieldLabel": "Auto-refresh feed",
    "AutoRefreshOnLabel": "On",
    "AutoRefreshOffLabel": "Off",
    "RefreshIntervalFieldLabel": "Refresh interval (minutes)",
    "LayoutFieldLabel": "Display Layout",
    "LayoutBannerLabel": "Banner",
    "LayoutCardLabel": "Card Grid",
    "LayoutListLabel": "List",
    "LayoutMinimalLabel": "Minimal",
    "LayoutMinimalDescription": "Text only without images, perfect for narrow columns",
    "ForceFallbackFieldLabel": "Always use fallback image",
    "ForceFallbackOnLabel": "Yes",
    "ForceFallbackOffLabel": "No",
    "FallbackUrlFieldLabel": "Fallback Image URL",
    "FallbackUrlDescription": "URL to use when no image is found in the feed",
    "ShowPubDateFieldLabel": "Show publication date",
    "ShowPubDateOnLabel": "Show",
    "ShowPubDateOffLabel": "Hide",
    "ShowDescriptionFieldLabel": "Show description",
    "ShowDescriptionOnLabel": "Show",
    "ShowDescriptionOffLabel": "Hide",
    "ShowSourceFieldLabel": "Show source",
    "ShowSourceOnLabel": "Show",
    "ShowSourceOffLabel": "Hide",
    "BannerSettingsGroupName": "Banner Settings",
    "AutoscrollFieldLabel": "Auto-scroll banner",
    "AutoscrollOnLabel": "On",
    "AutoscrollOffLabel": "Off",
    "IntervalFieldLabel": "Scroll interval (seconds)",
    "FilterSettingsGroupName": "Content Filter Settings",
    "FilterByKeywordsFieldLabel": "Filter items by keywords",
    "FilterByKeywordsOnLabel": "On",
    "FilterByKeywordsOffLabel": "Off", 
    "FilterKeywordsFieldLabel": "Filter keywords",
    "FilterKeywordsDescription": "Comma-separated list of keywords",
    "FilterModeFieldLabel": "Filter mode",
    "FilterModeIncludeLabel": "Include items containing keywords",
    "FilterModeExcludeLabel": "Exclude items containing keywords",
    "ErrorLoadingFeed": "Error loading RSS feed",
    "ErrorParsingFeed": "Error parsing RSS feed content",
    "RetryButtonText": "Try Again",
    "LoadingMessage": "Loading RSS feed...",
    "NoItemsMessage": "No items to display",
    "NoMatchingItemsMessage": "No items match your filter criteria",
    "DisplayGroupName": "Display Settings",
    "ImagesGroupName": "Images",
    "AdvancedGroupName": "Advanced Settings",
    "FeedUrlDescription": "Enter the URL of your RSS or Atom feed",
    "FeedUrlPlaceholder": "https://example.com/feed.rss",
    "LayoutBannerDescription": "Full-width rotating carousel",
    "LayoutCardDescription": "Grid of cards with images",
    "LayoutListDescription": "Compact list with thumbnails",
    "ShowPaginationFieldLabel": "Show navigation dots",
    "ShowPaginationOnLabel": "Show",
    "ShowPaginationOffLabel": "Hide",
    "ProxyUrlFieldLabel": "Proxy URL",
    "ProxyUrlDescription": "Optional: Configure a CORS proxy for reliable feed access",
    "ProxyUrlPlaceholder": "https://your-proxy.azurewebsites.net/api/proxy",
    "TestConnectionLabel": "Test connection",
    "TestingConnectionLabel": "Testing...",
    "ConnectionSuccessLabel": "Connection successful",
    "ConnectionFailedLabel": "Connection failed",
    "ProxyHelpLinkText": "Learn how to set up your own proxy",
    // Gallery layout strings
    "LayoutGalleryLabel": "Gallery",
    "LayoutGalleryDescription": "Image grid with titles on hover",
    "GallerySettingsGroupName": "Gallery Settings",
    "GalleryColumnsLabel": "Columns",
    "GalleryColumnsAuto": "Auto (responsive)",
    "GalleryTitlePositionLabel": "Title display",
    "GalleryTitleHover": "Show on hover",
    "GalleryTitleBelow": "Show below image",
    "GalleryTitleNone": "Hide titles",
    "GalleryAspectRatioLabel": "Image aspect ratio",
    "AspectRatio1x1": "Square (1:1)",
    "AspectRatio4x3": "Standard (4:3)",
    "AspectRatio16x9": "Widescreen (16:9)",
    "GalleryGapLabel": "Spacing between items",
    "GapSmall": "Small",
    "GapMedium": "Medium",
    "GapLarge": "Large",
    "GalleryNoImages": "No items with images to display",
    // Gallery preset
    "PresetPhotoGallery": "Photo Gallery",
    "PresetPhotoGalleryDescription": "Image grid with hover titles"
  }
});
