define([], function() {
  return {
    "PropertyPaneDescription": "Konfigurer innstillinger for RSS-visning",
    "BasicGroupName": "Feed-innstillinger",
    "TitleFieldLabel": "Webdel-tittel",
    "FeedUrlFieldLabel": "RSS-feed URL",
    "MaxItemsFieldLabel": "Maksimalt antall elementer",
    "AutoRefreshFieldLabel": "Automatisk oppdatering",
    "AutoRefreshOnLabel": "På",
    "AutoRefreshOffLabel": "Av",
    "RefreshIntervalFieldLabel": "Oppdateringsintervall (minutter)",
    "LayoutFieldLabel": "Visningsoppsett",
    "LayoutBannerLabel": "Banner",
    "LayoutCardLabel": "Kortvisning",
    "LayoutListLabel": "Liste",
    "ForceFallbackFieldLabel": "Bruk alltid reservebilde",
    "ForceFallbackOnLabel": "Ja",
    "ForceFallbackOffLabel": "Nei",
    "FallbackUrlFieldLabel": "Reservebilde URL",
    "FallbackUrlDescription": "URL som brukes når ingen bilde finnes i feeden",
    "ShowPubDateFieldLabel": "Vis publiseringsdato",
    "ShowPubDateOnLabel": "Vis",
    "ShowPubDateOffLabel": "Skjul",
    "ShowDescriptionFieldLabel": "Vis beskrivelse",
    "ShowDescriptionOnLabel": "Vis",
    "ShowDescriptionOffLabel": "Skjul",
    "BannerSettingsGroupName": "Banner-innstillinger",
    "AutoscrollFieldLabel": "Automatisk rulling",
    "AutoscrollOnLabel": "På",
    "AutoscrollOffLabel": "Av",
    "IntervalFieldLabel": "Rulleintervall (sekunder)",
    "ErrorLoadingFeed": "Feil ved lasting av RSS-feed",
    "ErrorParsingFeed": "Feil ved tolking av RSS-innhold",
    "ErrorFeedTimeout": "RSS-feeden svarte ikke i tide. Sjekk tilkoblingen og prøv igjen.",
    "ErrorFeedNetwork": "Kunne ikke nå RSS-feeden. Sjekk URL og nettverk.",
    "ErrorFeedNotFound": "Fant ikke RSS-feeden på den angitte adressen.",
    "ErrorFeedServer": "RSS-tjenesten er midlertidig utilgjengelig. Prøv igjen senere.",
    "RetryButtonText": "Prøv igjen",
    "LoadingMessage": "Laster RSS-feed...",
    "NoItemsMessage": "Ingen elementer å vise"
  }
});