
require("./CardLayout.module.css");
const styles = {
  'animate-fadeIn': 'animate-fadeIn_2d08f4bc',
  fadeIn: 'fadeIn_2d08f4bc',
  'animate-fadeOut': 'animate-fadeOut_2d08f4bc',
  fadeOut: 'fadeOut_2d08f4bc',
  'animate-slideUp': 'animate-slideUp_2d08f4bc',
  slideUp: 'slideUp_2d08f4bc',
  'animate-slideDown': 'animate-slideDown_2d08f4bc',
  slideDown: 'slideDown_2d08f4bc',
  'animate-slideLeft': 'animate-slideLeft_2d08f4bc',
  slideLeft: 'slideLeft_2d08f4bc',
  'animate-slideRight': 'animate-slideRight_2d08f4bc',
  slideRight: 'slideRight_2d08f4bc',
  'animate-scaleIn': 'animate-scaleIn_2d08f4bc',
  scaleIn: 'scaleIn_2d08f4bc',
  'animate-spin': 'animate-spin_2d08f4bc',
  spin: 'spin_2d08f4bc',
  'animate-pulse': 'animate-pulse_2d08f4bc',
  pulse: 'pulse_2d08f4bc',
  'animate-bounce': 'animate-bounce_2d08f4bc',
  bounce: 'bounce_2d08f4bc',
  'animate-shake': 'animate-shake_2d08f4bc',
  shake: 'shake_2d08f4bc',
  'sr-only': 'sr-only_2d08f4bc',
  'sr-only-focusable': 'sr-only-focusable_2d08f4bc',
  'focus-visible': 'focus-visible_2d08f4bc',
  'touch-target': 'touch-target_2d08f4bc',
  'reduced-motion': 'reduced-motion_2d08f4bc',
  'touch-action-manipulation': 'touch-action-manipulation_2d08f4bc',
  'touch-action-pan-x': 'touch-action-pan-x_2d08f4bc',
  'touch-action-pan-y': 'touch-action-pan-y_2d08f4bc',
  'touch-action-none': 'touch-action-none_2d08f4bc',
  'touch-interactive': 'touch-interactive_2d08f4bc',
  'touch-button': 'touch-button_2d08f4bc',
  pressed: 'pressed_2d08f4bc',
  'touch-card': 'touch-card_2d08f4bc',
  'touch-link': 'touch-link_2d08f4bc',
  'touch-list-item': 'touch-list-item_2d08f4bc',
  'touch-scroll': 'touch-scroll_2d08f4bc',
  'touch-scroll-horizontal': 'touch-scroll-horizontal_2d08f4bc',
  'touch-scroll-item': 'touch-scroll-item_2d08f4bc',
  'touch-input': 'touch-input_2d08f4bc',
  'ripple-container': 'ripple-container_2d08f4bc',
  ripple: 'ripple_2d08f4bc',
  'ripple-animation': 'ripple-animation_2d08f4bc',
  'is-pressed': 'is-pressed_2d08f4bc',
  'no-tap-highlight': 'no-tap-highlight_2d08f4bc',
  'no-select': 'no-select_2d08f4bc',
  cardLayout: 'cardLayout_2d08f4bc',
  card: 'card_2d08f4bc',
  scaleOut: 'scaleOut_2d08f4bc',
  shimmer: 'shimmer_2d08f4bc'
};

export default styles;
