const strings = {
  PropertyPaneDescription: "Configure your RSS feed",
  BasicGroupName: "Basic Settings",
  FeedUrlFieldLabel: "Feed URL",
  LayoutFieldLabel: "Layout",
  LayoutBannerLabel: "Banner",
  LayoutCardLabel: "Card",
  LayoutListLabel: "List",
  BannerSettingsGroupName: "Banner Settings",
  AutoscrollFieldLabel: "Enable Autoscroll",
  AutoscrollOnLabel: "On",
  AutoscrollOffLabel: "Off",
  IntervalFieldLabel: "Autoscroll Interval (seconds)",
  ForceFallbackFieldLabel: "Force Fallback Image",
  ForceFallbackOnLabel: "On",
  ForceFallbackOffLabel: "Off",
  FallbackUrlFieldLabel: "Fallback Image URL",
  FallbackUrlDescription: "Provide a URL for the fallback image.",
  MaxItemsFieldLabel: "Number of items to display",
  ShowPubDateFieldLabel: "Show publication date",
  ShowPubDateOnLabel: "On",
  ShowPubDateOffLabel: "Off",
  ShowDescriptionFieldLabel: "Show description",
  ShowDescriptionOnLabel: "On",
  ShowDescriptionOffLabel: "Off",
  TitleFieldLabel: "Web part title",
  AutoRefreshFieldLabel: "Auto-refresh feed",
  AutoRefreshOnLabel: "Enabled",
  AutoRefreshOffLabel: "Disabled",
  RefreshIntervalFieldLabel: "Refresh interval (minutes)",
  LoadingMessage: "Loading...",
};

export default strings;
